#[cfg(feature = "static")]
pub use libsqlite3_sys::{
    SQLITE_BLOB, SQLITE_CONSTRAINT, SQLITE_DETERMINISTIC, SQLITE_DIRECTONLY, SQLITE_DONE,
    SQLITE_ERROR, SQLITE_FLOAT, SQLITE_INNOCUOUS, SQLITE_INTEGER, SQLITE_INTERNAL, SQLITE_NULL,
    SQLITE_OK, SQLITE_OK_LOAD_PERMANENTLY, SQLITE_ROW, SQLITE_SUBTYPE, SQLITE_TEXT, SQLITE_UTF16,
    SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8,
};

#[cfg(all(not(feature = "static"), feature = "dynamic"))]
pub use sqlite3ext_sys::{
    SQLITE_BLOB, SQLITE_CONSTRAINT, SQLITE_DETERMINISTIC, SQLITE_DIRECTONLY, SQLITE_DONE,
    SQLITE_ERROR, SQLITE_FLOAT, SQLITE_INNOCUOUS, SQLITE_INTEGER, SQLITE_INTERNAL, SQLITE_NULL,
    SQLITE_OK, SQLITE_OK_LOAD_PERMANENTLY, SQLITE_ROW, SQLITE_SUBTYPE, SQLITE_TEXT, SQLITE_UTF16,
    SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8,
};
